// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aakarim/pland/ent/arbitrarysection"
	"github.com/aakarim/pland/ent/plan"
	"github.com/aakarim/pland/ent/predicate"
)

// ArbitrarySectionQuery is the builder for querying ArbitrarySection entities.
type ArbitrarySectionQuery struct {
	config
	limit         *int
	offset        *int
	unique        *bool
	order         []OrderFunc
	fields        []string
	predicates    []predicate.ArbitrarySection
	withPlan      *PlanQuery
	modifiers     []func(*sql.Selector)
	loadTotal     []func(context.Context, []*ArbitrarySection) error
	withNamedPlan map[string]*PlanQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ArbitrarySectionQuery builder.
func (asq *ArbitrarySectionQuery) Where(ps ...predicate.ArbitrarySection) *ArbitrarySectionQuery {
	asq.predicates = append(asq.predicates, ps...)
	return asq
}

// Limit adds a limit step to the query.
func (asq *ArbitrarySectionQuery) Limit(limit int) *ArbitrarySectionQuery {
	asq.limit = &limit
	return asq
}

// Offset adds an offset step to the query.
func (asq *ArbitrarySectionQuery) Offset(offset int) *ArbitrarySectionQuery {
	asq.offset = &offset
	return asq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (asq *ArbitrarySectionQuery) Unique(unique bool) *ArbitrarySectionQuery {
	asq.unique = &unique
	return asq
}

// Order adds an order step to the query.
func (asq *ArbitrarySectionQuery) Order(o ...OrderFunc) *ArbitrarySectionQuery {
	asq.order = append(asq.order, o...)
	return asq
}

// QueryPlan chains the current query on the "plan" edge.
func (asq *ArbitrarySectionQuery) QueryPlan() *PlanQuery {
	query := &PlanQuery{config: asq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := asq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := asq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(arbitrarysection.Table, arbitrarysection.FieldID, selector),
			sqlgraph.To(plan.Table, plan.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, arbitrarysection.PlanTable, arbitrarysection.PlanPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(asq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ArbitrarySection entity from the query.
// Returns a *NotFoundError when no ArbitrarySection was found.
func (asq *ArbitrarySectionQuery) First(ctx context.Context) (*ArbitrarySection, error) {
	nodes, err := asq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{arbitrarysection.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (asq *ArbitrarySectionQuery) FirstX(ctx context.Context) *ArbitrarySection {
	node, err := asq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ArbitrarySection ID from the query.
// Returns a *NotFoundError when no ArbitrarySection ID was found.
func (asq *ArbitrarySectionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = asq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{arbitrarysection.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (asq *ArbitrarySectionQuery) FirstIDX(ctx context.Context) int {
	id, err := asq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ArbitrarySection entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ArbitrarySection entity is found.
// Returns a *NotFoundError when no ArbitrarySection entities are found.
func (asq *ArbitrarySectionQuery) Only(ctx context.Context) (*ArbitrarySection, error) {
	nodes, err := asq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{arbitrarysection.Label}
	default:
		return nil, &NotSingularError{arbitrarysection.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (asq *ArbitrarySectionQuery) OnlyX(ctx context.Context) *ArbitrarySection {
	node, err := asq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ArbitrarySection ID in the query.
// Returns a *NotSingularError when more than one ArbitrarySection ID is found.
// Returns a *NotFoundError when no entities are found.
func (asq *ArbitrarySectionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = asq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{arbitrarysection.Label}
	default:
		err = &NotSingularError{arbitrarysection.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (asq *ArbitrarySectionQuery) OnlyIDX(ctx context.Context) int {
	id, err := asq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ArbitrarySections.
func (asq *ArbitrarySectionQuery) All(ctx context.Context) ([]*ArbitrarySection, error) {
	if err := asq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return asq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (asq *ArbitrarySectionQuery) AllX(ctx context.Context) []*ArbitrarySection {
	nodes, err := asq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ArbitrarySection IDs.
func (asq *ArbitrarySectionQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := asq.Select(arbitrarysection.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (asq *ArbitrarySectionQuery) IDsX(ctx context.Context) []int {
	ids, err := asq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (asq *ArbitrarySectionQuery) Count(ctx context.Context) (int, error) {
	if err := asq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return asq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (asq *ArbitrarySectionQuery) CountX(ctx context.Context) int {
	count, err := asq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (asq *ArbitrarySectionQuery) Exist(ctx context.Context) (bool, error) {
	if err := asq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return asq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (asq *ArbitrarySectionQuery) ExistX(ctx context.Context) bool {
	exist, err := asq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ArbitrarySectionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (asq *ArbitrarySectionQuery) Clone() *ArbitrarySectionQuery {
	if asq == nil {
		return nil
	}
	return &ArbitrarySectionQuery{
		config:     asq.config,
		limit:      asq.limit,
		offset:     asq.offset,
		order:      append([]OrderFunc{}, asq.order...),
		predicates: append([]predicate.ArbitrarySection{}, asq.predicates...),
		withPlan:   asq.withPlan.Clone(),
		// clone intermediate query.
		sql:    asq.sql.Clone(),
		path:   asq.path,
		unique: asq.unique,
	}
}

// WithPlan tells the query-builder to eager-load the nodes that are connected to
// the "plan" edge. The optional arguments are used to configure the query builder of the edge.
func (asq *ArbitrarySectionQuery) WithPlan(opts ...func(*PlanQuery)) *ArbitrarySectionQuery {
	query := &PlanQuery{config: asq.config}
	for _, opt := range opts {
		opt(query)
	}
	asq.withPlan = query
	return asq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ArbitrarySection.Query().
//		GroupBy(arbitrarysection.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (asq *ArbitrarySectionQuery) GroupBy(field string, fields ...string) *ArbitrarySectionGroupBy {
	grbuild := &ArbitrarySectionGroupBy{config: asq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := asq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return asq.sqlQuery(ctx), nil
	}
	grbuild.label = arbitrarysection.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ArbitrarySection.Query().
//		Select(arbitrarysection.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (asq *ArbitrarySectionQuery) Select(fields ...string) *ArbitrarySectionSelect {
	asq.fields = append(asq.fields, fields...)
	selbuild := &ArbitrarySectionSelect{ArbitrarySectionQuery: asq}
	selbuild.label = arbitrarysection.Label
	selbuild.flds, selbuild.scan = &asq.fields, selbuild.Scan
	return selbuild
}

func (asq *ArbitrarySectionQuery) prepareQuery(ctx context.Context) error {
	for _, f := range asq.fields {
		if !arbitrarysection.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if asq.path != nil {
		prev, err := asq.path(ctx)
		if err != nil {
			return err
		}
		asq.sql = prev
	}
	return nil
}

func (asq *ArbitrarySectionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ArbitrarySection, error) {
	var (
		nodes       = []*ArbitrarySection{}
		_spec       = asq.querySpec()
		loadedTypes = [1]bool{
			asq.withPlan != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*ArbitrarySection).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &ArbitrarySection{config: asq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(asq.modifiers) > 0 {
		_spec.Modifiers = asq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, asq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := asq.withPlan; query != nil {
		if err := asq.loadPlan(ctx, query, nodes,
			func(n *ArbitrarySection) { n.Edges.Plan = []*Plan{} },
			func(n *ArbitrarySection, e *Plan) { n.Edges.Plan = append(n.Edges.Plan, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range asq.withNamedPlan {
		if err := asq.loadPlan(ctx, query, nodes,
			func(n *ArbitrarySection) { n.appendNamedPlan(name) },
			func(n *ArbitrarySection, e *Plan) { n.appendNamedPlan(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range asq.loadTotal {
		if err := asq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (asq *ArbitrarySectionQuery) loadPlan(ctx context.Context, query *PlanQuery, nodes []*ArbitrarySection, init func(*ArbitrarySection), assign func(*ArbitrarySection, *Plan)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*ArbitrarySection)
	nids := make(map[int]map[*ArbitrarySection]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(arbitrarysection.PlanTable)
		s.Join(joinT).On(s.C(plan.FieldID), joinT.C(arbitrarysection.PlanPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(arbitrarysection.PlanPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(arbitrarysection.PlanPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]interface{}, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]interface{}{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []interface{}) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*ArbitrarySection]struct{}{byID[outValue]: struct{}{}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "plan" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (asq *ArbitrarySectionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := asq.querySpec()
	if len(asq.modifiers) > 0 {
		_spec.Modifiers = asq.modifiers
	}
	_spec.Node.Columns = asq.fields
	if len(asq.fields) > 0 {
		_spec.Unique = asq.unique != nil && *asq.unique
	}
	return sqlgraph.CountNodes(ctx, asq.driver, _spec)
}

func (asq *ArbitrarySectionQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := asq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (asq *ArbitrarySectionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   arbitrarysection.Table,
			Columns: arbitrarysection.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: arbitrarysection.FieldID,
			},
		},
		From:   asq.sql,
		Unique: true,
	}
	if unique := asq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := asq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, arbitrarysection.FieldID)
		for i := range fields {
			if fields[i] != arbitrarysection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := asq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := asq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := asq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := asq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (asq *ArbitrarySectionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(asq.driver.Dialect())
	t1 := builder.Table(arbitrarysection.Table)
	columns := asq.fields
	if len(columns) == 0 {
		columns = arbitrarysection.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if asq.sql != nil {
		selector = asq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if asq.unique != nil && *asq.unique {
		selector.Distinct()
	}
	for _, p := range asq.predicates {
		p(selector)
	}
	for _, p := range asq.order {
		p(selector)
	}
	if offset := asq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := asq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedPlan tells the query-builder to eager-load the nodes that are connected to the "plan"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (asq *ArbitrarySectionQuery) WithNamedPlan(name string, opts ...func(*PlanQuery)) *ArbitrarySectionQuery {
	query := &PlanQuery{config: asq.config}
	for _, opt := range opts {
		opt(query)
	}
	if asq.withNamedPlan == nil {
		asq.withNamedPlan = make(map[string]*PlanQuery)
	}
	asq.withNamedPlan[name] = query
	return asq
}

// ArbitrarySectionGroupBy is the group-by builder for ArbitrarySection entities.
type ArbitrarySectionGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (asgb *ArbitrarySectionGroupBy) Aggregate(fns ...AggregateFunc) *ArbitrarySectionGroupBy {
	asgb.fns = append(asgb.fns, fns...)
	return asgb
}

// Scan applies the group-by query and scans the result into the given value.
func (asgb *ArbitrarySectionGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := asgb.path(ctx)
	if err != nil {
		return err
	}
	asgb.sql = query
	return asgb.sqlScan(ctx, v)
}

func (asgb *ArbitrarySectionGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range asgb.fields {
		if !arbitrarysection.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := asgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := asgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (asgb *ArbitrarySectionGroupBy) sqlQuery() *sql.Selector {
	selector := asgb.sql.Select()
	aggregation := make([]string, 0, len(asgb.fns))
	for _, fn := range asgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(asgb.fields)+len(asgb.fns))
		for _, f := range asgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(asgb.fields...)...)
}

// ArbitrarySectionSelect is the builder for selecting fields of ArbitrarySection entities.
type ArbitrarySectionSelect struct {
	*ArbitrarySectionQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ass *ArbitrarySectionSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ass.prepareQuery(ctx); err != nil {
		return err
	}
	ass.sql = ass.ArbitrarySectionQuery.sqlQuery(ctx)
	return ass.sqlScan(ctx, v)
}

func (ass *ArbitrarySectionSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ass.sql.Query()
	if err := ass.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
